import { Game } from './engine.js';
import { bindKeyboard, bindTouchControls } from './controls.js';
import { renderBoard, renderPreview } from './renderer.js';
import { getTheme, makeCustomTheme } from './themes.js';
import { loadProfile, saveProfile } from './storage.js';
const $=(selector)=>document.querySelector(selector);
const els={canvas:$('#gameCanvas'),hold:$('#holdCanvas'),next:[$('#nextCanvas0'),$('#nextCanvas1'),$('#nextCanvas2')],score:$('#scoreValue'),best:$('#bestValue'),level:$('#levelValue'),lines:$('#linesValue'),theme:$('#themeSelect'),difficulty:$('#difficultySelect'),customAccent:$('#customAccent'),customColorLabel:$('#customColorLabel'),newGame:$('#newGameButton'),install:$('#installButton'),pause:$('#pauseButton'),overlay:$('#gameOverlay'),overlayKicker:$('#overlayKicker'),overlayTitle:$('#overlayTitle'),overlayText:$('#overlayText'),overlayAction:$('#overlayAction'),connection:$('#connectionStatus'),themeColor:document.querySelector('meta[name="theme-color"]')};
let profile=loadProfile();let game=new Game({difficulty:profile.difficulty});let theme=resolveTheme();let lastTick=performance.now();let installPrompt=null;
function resolveTheme(){return profile.theme==='custom'?makeCustomTheme(profile.customAccent):getTheme(profile.theme);}
function applyTheme(){theme=resolveTheme();document.body.dataset.theme=profile.theme;const root=document.documentElement;const vars={'--accent':theme.accent,'--accent-2':theme.accent2,'--sky-top':theme.skyTop,'--sky-bottom':theme.skyBottom,'--horizon':theme.horizon,'--panel':theme.panel,'--text':theme.text,'--muted':theme.muted};Object.entries(vars).forEach(([key,value])=>root.style.setProperty(key,value));els.themeColor?.setAttribute('content',theme.skyTop);els.customColorLabel.hidden=profile.theme!=='custom';}
function updateBest(score){if(score<=profile.bestScore)return;profile=saveProfile({...profile,bestScore:score});}
function render(){const snapshot=game.snapshot();updateBest(snapshot.score);renderBoard(els.canvas,snapshot,theme);renderPreview(els.hold,snapshot.holdType,theme);snapshot.nextTypes.forEach((type,index)=>renderPreview(els.next[index],type,theme));els.score.textContent=snapshot.score.toLocaleString('fr-FR');els.best.textContent=profile.bestScore.toLocaleString('fr-FR');els.level.textContent=String(snapshot.level+1);els.lines.textContent=String(snapshot.lines);els.pause.textContent=snapshot.paused?'▶':'Ⅱ';els.pause.setAttribute('aria-label',snapshot.paused?'Reprendre la partie':'Mettre en pause');updateOverlay(snapshot);}
function updateOverlay(snapshot){if(snapshot.gameOver){els.overlay.hidden=false;els.overlayKicker.textContent='Fin de partie';els.overlayTitle.textContent=snapshot.score>0?'Belle vague !':'La nuit continue';els.overlayText.textContent=`Score ${snapshot.score.toLocaleString('fr-FR')} · ${snapshot.lines} ligne${snapshot.lines>1?'s':''}.`;els.overlayAction.textContent='Rejouer';return;}if(snapshot.paused){els.overlay.hidden=false;els.overlayKicker.textContent='Pause';els.overlayTitle.textContent='Partie en pause';els.overlayText.textContent='Reprends quand tu veux.';els.overlayAction.textContent='Reprendre';return;}els.overlay.hidden=true;}
function newGame(){game=new Game({difficulty:profile.difficulty});lastTick=performance.now();render();}
function handleAction(action){if(game.gameOver&&action!=='pause')return;switch(action){case'left':game.move(-1,0);break;case'right':game.move(1,0);break;case'down':game.softDrop();break;case'rotate':game.rotate(1);break;case'drop':game.hardDrop();break;case'hold':game.hold();break;case'pause':game.togglePause();break;default:return;}lastTick=performance.now();render();}
function loop(now){if(!game.paused&&!game.gameOver&&now-lastTick>=game.dropInterval){game.tick();lastTick=now;render();}requestAnimationFrame(loop);}
function syncOnlineStatus(){const online=navigator.onLine;els.connection.textContent=online?'En ligne':'Hors ligne · partie disponible';els.connection.dataset.online=online?'true':'false';}
function registerPwa(){if('serviceWorker'in navigator){window.addEventListener('load',()=>{navigator.serviceWorker.register('./service-worker.js').catch((error)=>console.warn('Service worker non enregistré',error));});}window.addEventListener('beforeinstallprompt',(event)=>{event.preventDefault();installPrompt=event;els.install.hidden=false;});window.addEventListener('appinstalled',()=>{installPrompt=null;els.install.hidden=true;});els.install.addEventListener('click',async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;els.install.hidden=true;});}
els.theme.value=profile.theme;els.difficulty.value=profile.difficulty;els.customAccent.value=profile.customAccent;applyTheme();
els.theme.addEventListener('change',()=>{profile=saveProfile({...profile,theme:els.theme.value});applyTheme();render();});
els.customAccent.addEventListener('input',()=>{profile=saveProfile({...profile,theme:'custom',customAccent:els.customAccent.value});els.theme.value='custom';applyTheme();render();});
els.difficulty.addEventListener('change',()=>{profile=saveProfile({...profile,difficulty:els.difficulty.value});game.setDifficulty(profile.difficulty);lastTick=performance.now();});
els.newGame.addEventListener('click',newGame);els.overlayAction.addEventListener('click',()=>{if(game.gameOver)newGame();else handleAction('pause');});
bindKeyboard(handleAction);bindTouchControls(document,handleAction);window.addEventListener('online',syncOnlineStatus);window.addEventListener('offline',syncOnlineStatus);window.addEventListener('resize',render,{passive:true});syncOnlineStatus();registerPwa();render();requestAnimationFrame(loop);
