import { BOARD_HEIGHT, BOARD_WIDTH, pieceCells } from './engine.js';
import { piecePalette } from './themes.js';
export function boardPixelSize(maxWidth){const safeWidth=Math.max(100,Number(maxWidth)||300);const cell=Math.max(10,Math.floor(safeWidth/BOARD_WIDTH));return {width:cell*BOARD_WIDTH,height:cell*BOARD_HEIGHT,cell};}
function ensureCanvasResolution(canvas){const rect=canvas.getBoundingClientRect();const dpr=Math.min(globalThis.devicePixelRatio||1,2);const width=Math.max(1,Math.round(rect.width*dpr)),height=Math.max(1,Math.round(rect.height*dpr));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return {ctx,width:rect.width,height:rect.height};}
function roundedRect(ctx,x,y,w,h,radius){const r=Math.min(radius,w/2,h/2);ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
function drawBlock(ctx,x,y,size,type,theme,{ghost=false,alpha=1}={}){const [light,dark]=piecePalette[type]??[theme.accent,theme.accent2];const inset=Math.max(1.5,size*.07),rx=x*size+inset,ry=y*size+inset,rw=size-inset*2,rh=size-inset*2;if(ghost){ctx.save();ctx.globalAlpha=.45;ctx.strokeStyle=light;ctx.lineWidth=Math.max(1.4,size*.07);roundedRect(ctx,rx+1,ry+1,rw-2,rh-2,size*.14);ctx.stroke();ctx.restore();return;}ctx.save();ctx.globalAlpha=alpha;ctx.shadowColor=theme.glow;ctx.shadowBlur=Math.max(3,size*.24);const gradient=ctx.createLinearGradient(rx,ry,rx+rw,ry+rh);gradient.addColorStop(0,light);gradient.addColorStop(.55,light);gradient.addColorStop(1,dark);ctx.fillStyle=gradient;roundedRect(ctx,rx,ry,rw,rh,size*.15);ctx.fill();ctx.shadowBlur=0;const bevel=Math.max(1,size*.06);ctx.strokeStyle='rgba(255,255,255,.48)';ctx.lineWidth=bevel;ctx.beginPath();ctx.moveTo(rx+bevel,ry+rh-bevel);ctx.lineTo(rx+bevel,ry+bevel);ctx.lineTo(rx+rw-bevel,ry+bevel);ctx.stroke();ctx.strokeStyle='rgba(0,0,0,.28)';ctx.beginPath();ctx.moveTo(rx+rw-bevel,ry+bevel);ctx.lineTo(rx+rw-bevel,ry+rh-bevel);ctx.lineTo(rx+bevel,ry+rh-bevel);ctx.stroke();ctx.restore();}
export function renderBoard(canvas,snapshot,theme){const {ctx,width,height}=ensureCanvasResolution(canvas);const cell=Math.min(width/BOARD_WIDTH,height/BOARD_HEIGHT);ctx.clearRect(0,0,width,height);const boardGradient=ctx.createLinearGradient(0,0,0,height);boardGradient.addColorStop(0,'rgba(2, 7, 15, .90)');boardGradient.addColorStop(1,'rgba(3, 12, 25, .96)');ctx.fillStyle=boardGradient;ctx.fillRect(0,0,width,height);ctx.strokeStyle=theme.grid;ctx.lineWidth=1;for(let x=1;x<BOARD_WIDTH;x+=1){ctx.beginPath();ctx.moveTo(x*cell,0);ctx.lineTo(x*cell,BOARD_HEIGHT*cell);ctx.stroke();}for(let y=1;y<BOARD_HEIGHT;y+=1){ctx.beginPath();ctx.moveTo(0,y*cell);ctx.lineTo(BOARD_WIDTH*cell,y*cell);ctx.stroke();}snapshot.board.forEach((row,y)=>row.forEach((type,x)=>{if(type)drawBlock(ctx,x,y,cell,type,theme);}));if(snapshot.active){const ghostPiece={...snapshot.active,y:snapshot.ghostY};pieceCells(ghostPiece).forEach(([x,y])=>{if(y>=0)drawBlock(ctx,x,y,cell,snapshot.active.type,theme,{ghost:true});});pieceCells(snapshot.active).forEach(([x,y])=>{if(y>=0)drawBlock(ctx,x,y,cell,snapshot.active.type,theme);});}const edge=ctx.createLinearGradient(0,0,width,0);edge.addColorStop(0,theme.accent);edge.addColorStop(.5,theme.accent2);edge.addColorStop(1,theme.accent);ctx.strokeStyle=edge;ctx.lineWidth=2;ctx.strokeRect(1,1,width-2,height-2);}
const PREVIEW_SHAPES={I:[[0,1],[1,1],[2,1],[3,1]],J:[[0,0],[0,1],[1,1],[2,1]],L:[[2,0],[0,1],[1,1],[2,1]],O:[[1,0],[2,0],[1,1],[2,1]],S:[[1,0],[2,0],[0,1],[1,1]],T:[[1,0],[0,1],[1,1],[2,1]],Z:[[0,0],[1,0],[1,1],[2,1]]};
export function renderPreview(canvas,type,theme){const {ctx,width,height}=ensureCanvasResolution(canvas);ctx.clearRect(0,0,width,height);if(!type)return;const cell=Math.min(width,height)/5,cells=PREVIEW_SHAPES[type]??[],xs=cells.map(([x])=>x),ys=cells.map(([,y])=>y),shapeWidth=(Math.max(...xs)-Math.min(...xs)+1)*cell,shapeHeight=(Math.max(...ys)-Math.min(...ys)+1)*cell,offsetX=(width-shapeWidth)/2/cell-Math.min(...xs),offsetY=(height-shapeHeight)/2/cell-Math.min(...ys);cells.forEach(([x,y])=>drawBlock(ctx,x+offsetX,y+offsetY,cell,type,theme));}
